title: Utiliser des instructions conditionnelles
hero_image: images/banner.png
description: Utiliser des instructions conditionnelles en JavaScript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Utiliser des instructions conditionnelles
